### ISSUE TITLE
triton error

### ISSUE THREAD

**Issue by missingthl** [state-spaces/mamba#365]
![Screenshot from 2024-06-05 22-23-59](https://github.com/state-spaces/mamba/assets/89624489/fa4ae161-6a93-4a9b-b9d1-358783bfc30e)

Encountered an error here
RuntimeError: Triton Error [CUDA]: misaligned address 
：-（

**Comment by Kevin-naticl** [comment]
trition>=2.1.0 is needed, but I have another trition problem.

**Comment by Kevin-naticl** [comment]
Here is my issues:https://github.com/state-spaces/mamba/issues/370

**Comment by mahao18cm** [comment]
Do you solve this problems? I still have this problems.

**Comment by Kevin-naticl** [comment]
I still have this problem. Maybe try to find out the problem of training code. I'm doing this right now.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "state-spaces/mamba"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月16日(星期天) 中午1:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [state-spaces/mamba] triton error (Issue #365)





 
Do you solve this problems? I still have this problems.

**Comment by missingthl** [comment]
> trition>=2.1.0 is needed, but I have another trition problem.

My device is also 4090. My environment is CUDA 11.8, PyTorch 2.1.2, causal-conv1d 1.1.3.
can run mamba1 correctly. I am trying to reconfigure the environment. I saw your problem, hope it's an environment configuration issue; otherwise, it might be too complicated to solve.

**Comment by mahao18cm** [comment]
> I still have this problem. Maybe try to find out the problem of training code. I'm doing this right now.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "state-spaces/mamba" ***@***.***&gt;; 发送时间:&nbsp;2024年6月16日(星期天) 中午1:52 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [state-spaces/mamba] triton error (Issue #365) Do you solve this problems? I still have this problems. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

Actually mamba2 is  a trash compared to mamba1. I just replace mamba1 now. To my surprise, mamba2 need more memory.

**Comment by Kevin-naticl** [comment]
Thx for reply. My device is also 4090. When I set my model eval mode, it works fine. However when I use multi-GPU to train it, it has the problem. I'm trying to rewrite my train code.&nbsp;
&nbsp;


康博意
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月16日(星期天) 下午2:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [state-spaces/mamba] triton error (Issue #365)














  
trition&gt;=2.1.0 is needed, but I have another trition problem.
  
My device is also 4090. My environment is CUDA 11.8, PyTorch 2.1.2, causal-conv1d 1.1.3.
 can run mamba1 correctly. I am trying to reconfigure the environment. I saw your problem, hope it's an environment configuration issue; otherwise, it might be too complicated to solve.

**Comment by weili419** [comment]
Hello, has the suspected 'memory misalignment' error been resolved? Can you share your experience？

**Comment by missingthl** [comment]
> 您好，疑似的“内存未对齐”错误是否已解决？您能分享一下您的经验吗？

可能是triton版本的问题，我去mamba的项目和causal的项目去找对应的版本重新配环境跑通了

**Comment by Kevin-naticl** [comment]
应该就是和cuda版本还有triton版本都有关系。看作者发布的包的话，cuda12.2以及之后应该和之前有一些区别。你可以试一下。&nbsp;


康博意
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月3日(星期二) 下午2:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [state-spaces/mamba] triton error (Issue #365)














 
Hello, has the suspected 'memory misalignment' error been resolved? Can you share your experience？
