### ISSUE TITLE
When I run mamba2 : ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Rruixu** [state-spaces/mamba#450]
import selective_scan_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

my cuda : 12.1

Is cuda 12.+ dont match mamba2 ?

**Comment by JerayuT** [comment]
I also ran into the same problem. Did you solve end up figuring it out?

**Comment by RohollahHS** [comment]
> @Rruixu I also ran into the same problem. Did you solve end up figuring it out?

Hi. Did you solve this issue?

**Comment by JerayuT** [comment]
I'm not sure if this will help, but I ran into this issue when I tried after installing triton separately in a conda environment to make it match their triton version. I fixed it but just creating a new environment, using the latest version of torch and installing causal-conv1d followed by mamba-ssm and it seemed to fix the issue.

**Comment by rozariwang** [comment]
> I'm not sure if this will help, but I ran into this issue when I tried after installing triton separately in a conda environment to make it match their triton version. I fixed it but just creating a new environment, using the latest version of torch and installing causal-conv1d followed by mamba-ssm and it seemed to fix the issue.

Which cuda version are you using?

**Comment by JerayuT** [comment]
> > I'm not sure if this will help, but I ran into this issue when I tried after installing triton separately in a conda environment to make it match their triton version. I fixed it but just creating a new environment, using the latest version of torch and installing causal-conv1d followed by mamba-ssm and it seemed to fix the issue.
> 
> Which cuda version are you using?

I'm using version 12.4

**Comment by JerayuT** [comment]
I'm using setuptools 0.9.8 and installing mamba-ssm using pip. You might have to delete your site-packages? Here are the exact steps I took to fix this issue.

Deleted all python site-packages (From what I saw creating a new conda environment will still refer to packages in here which is why it couldn't find the correct libcudart file so I opted to delete everything and reinstall them)
Created a conda environment (I used python=3.9.5)
conda installed cuda-nvcc
pip install torch, causal-conv1d >= 1.4.0 and then mamba-ssm using --no-cache-dir.

After that I could run mamba 2. Hope this helps!

**Comment by rozariwang** [comment]
Thank you so much! I'm using Docker, and it turned out that I had to switch the base image. basically what you did as well! Thanks again
