### ISSUE TITLE
Cuda 12.4 - ImportError: libcudart.so.12: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by rozariwang** [state-spaces/mamba#567]
pytorch 2.4.0
setuptools 69.5.1
cuda 12.4

Hi,
 
I am trying to run Mamba on a server using a Docker image. The server machines are using Cuda 12.4. 
When I try to run the model, I get the following output. I wonder if it is related to incompatibilities with Cuda or Pytorch.  

```
import selective_scan_cuda
ImportError: libcudart.so.12: cannot open shared object file: No such file or directory
```

I can see there is [no wheel for Cuda 12.4](https://github.com/state-spaces/mamba/releases). Is it possible to publish a wheel for Cuda 12.4? 
Somebody else is asking for the same [here](https://github.com/state-spaces/mamba/pull/504). 

Thanks a lot.

**Comment by dongzhue** [comment]
I also encountered this problem. Could you please share how you solved it?

**Comment by rozariwang** [comment]
Hi @dongzhue, 

I believe I eventually solved it by changing the base image to [nvidia/cuda:12.4.0-devel-ubuntu22.04](https://hub.docker.com/layers/nvidia/cuda/12.4.0-devel-ubuntu22.04/images/sha256-456c919bec924d6add510e2ba23fd56f16d7d7d5a4d533878cc395d2175eb4d0?context=explore). I hope this helps~

**Comment by dongzhue** [comment]
> Hi @dongzhue,
> 
> I believe I eventually solved it by changing the base image to [nvidia/cuda:12.4.0-devel-ubuntu22.04](https://hub.docker.com/layers/nvidia/cuda/12.4.0-devel-ubuntu22.04/images/sha256-456c919bec924d6add510e2ba23fd56f16d7d7d5a4d533878cc395d2175eb4d0?context=explore). I hope this helps~

Thanks a lot!
