### ISSUE TITLE
Has anyone successfully configured the Manba environment on Kaggle? I have been unable to install it

### ISSUE THREAD

**Issue by ZhangWeiOvO** [state-spaces/mamba#668]
!pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu121 
!pip uninstall mamba-ssm causal-conv1d 
!pip install causal-conv1d && pip install mamba-ssm

RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by soroushoraki** [comment]
@ZhangWeiOvO Did you resolve this issue?

**Comment by ZhangWeiOvO** [comment]
@soroushoraki I have tried many methods, but still failed

**Comment by srijiths** [comment]
I am able to run Mamba in Kaggle notebook with this.

```python
!pip install mamba-ssm
!pip install causal-conv1d>=1.4.0
!pip install triton
!pip install datasets evaluate accelerate
!pip install torch --index-url https://download.pytorch.org/whl/cu121
`
And selected GPU T4x2 in the notebook

**Comment by ZhangWeiOvO** [comment]
> I am able to run Mamba in Kaggle notebook with this.
> 
> !pip install mamba-ssm
> !pip install causal-conv1d>=1.4.0
> !pip install triton
> !pip install datasets evaluate accelerate
> !pip install torch --index-url https://download.pytorch.org/whl/cu121
> 
> And selected GPU T4x2 in the notebook

Thank you, I successfully ran mamba in this environment, but when I switched to mamba2, an error occurred.

**Comment by srijiths** [comment]
Haven't tried mamba2 yet.

**Comment by iiqra-khan** [comment]
> I am able to run Mamba in Kaggle notebook with this.
> 
> !pip install mamba-ssm
> !pip install causal-conv1d>=1.4.0
> !pip install triton
> !pip install torch --index-url https://download.pytorch.org/whl/cu121
> And selected GPU T4x2 in the notebook

i have tried this but mine says it failed to build wheel did you do any other changes or settings too

**Comment by MHamdyK** [comment]
> > I am able to run Mamba in Kaggle notebook with this.
> > !pip install mamba-ssm
> > !pip install causal-conv1d>=1.4.0
> > !pip install triton
> > !pip install torch --index-url https://download.pytorch.org/whl/cu121
> > And selected GPU T4x2 in the notebook
> 
> i have tried this but mine says it failed to build wheel did you do any other changes or settings too

@iiqra-khan any luck getting it to work?

**Comment by srijiths** [comment]
The libs are keep on changing. It got failed for me too. But there is a trick to get it work. I added `--no-build-isolation` for `mamba-ssm` and it works for me

```
!pip install mamba-ssm --no-build-isolation
!pip install causal-conv1d>=1.1.0
!pip install triton
!pip install datasets evaluate accelerate
!pip install torch --index-url https://download.pytorch.org/whl/cu121
```

**Comment by iiqra-khan** [comment]
@MHamdyK i was able to do it like this

pip install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu121
pip install causal-conv1d==1.4.0 && pip install mamba-ssm==2.2.2
pip install torch_geometric
